name: Publish to Packagist

on:
  push:
    tags: [ '*' ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Packagist Update
        uses: hotaruma/packagist-sync@v1.0.1
        with:
          api-token: ${{ secrets.PACKAGIST_TOKEN }}
